CREATE TABLE USERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL
);

INSERT INTO USERS (NAME, PASSWORD, USERNAME) VALUES ('User', '$2a$10$3tZ51smBnYxQE3akMdEtNefKZVl6xyLTmkcUTlBbPQ3w5Uw/uEvYW', 'user@gmail.com');